//TEST CREATE TABLE

CREATE TABLE TEST(
	TEST NUMBER,
	TEST2 VARCHAR2(200)
);

SELECT * FROM TEST;

SELECT * FROM TAB;
SELECT * FROM BLOG_NEWSBOARD;

SELECT * FROM V_BLOG_LIST_DESC;
SELECT * FROM V_BLOG_LIST;